<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Inspection.Core/Inspection.Core.csproj" />
    <ProjectReference Include="../Inspection.Infrastructure/Inspection.Infrastructure.csproj" />
  </ItemGroup>
</Project>
